### ISSUE TITLE
pip install failing

### ISSUE THREAD

**Issue by pbhasker** [MonkeySeatRacing/f1-22-telemetry#3]
When I try to install this module with `pip install f1-22-telemetry`

I get the following error.

```
Collecting f1-22-telemetry
  Could not find a version that satisfies the requirement f1-22-telemetry (from versions: )
No matching distribution found for f1-22-telemetry
```

Any suggestions?

**Comment by rcastley** [comment]
@pbhasker Try `python3 -m pip install f1-22-telemetry`

**Comment by chrishannam** [comment]
@pbhasker which version of python are you running?

**Comment by pbhasker** [comment]
@rcastley  That fixed it for me! Thanks. Resolving.
